sudo: false
language: node_js
node_js:
  - '8'

script:
  - npm run test:coverage-ci

notifications:
  slack:
    rooms:
      secure: p6bTA+Tfevko/4mdKjSB1xv8cCKJbMut6o6J49X2nXecNdiZ3tseA0ctbXsMgsQgXoU74imLtNOqC5ufs83TLy4D+J4vnfJ8XPCAecTZtq3qFl/8/QFB4ozxyVfVIaxhIVDJGcrQOWARB/NLk7v1arCHjyD3eVabAPGfwhtRxOhoD2c7B3mhQq0qNh1q7MHhWPWG8bmpbZeZfjvheRjpj6uNh7unxg3sY3AiMyg//W0vgub/LfZwhpS1YCbUmKhmmmdT3wqBH4+Q3LMcNN2tcVfBI/ajhR9akpuhxRorO9/a49WQ5HeHEPAbAC4bjk0/V9XiFaiKYk+vJowEX8i1mladvBiYQcLfUPl2tg2zxgAs9aXigMLd+6F9rm2tx039wKp7zKAcNioR5IcJcLrmOarsJivVyiO/DBC0IsJ9GPCk5Me6GV5dIOOCG/IywW3sF5FMbcBGZaJEf2AV+m2eETbXXcJyOyci5OCVr2oaAdaphf+kzesSt5Ir05I6kxDBh6czRHkBJ+KoLtGpnO+4YrMEuPPpZSqe5BCKzrLixggcGfk3OLUek1+DVTfdGDwUZf8p7kmXYm9IWqJ36kdg1vI9B5aZh6+ZW0RXqZeAImhn5mkkQTmyoTmX0uo8HvrBtAOQI9Gss9UkP5BYwpmxTBGvgCqwwCRyDKZAF2GFGBU=
    on_start: never
    on_success: change
    on_failure: always
    on_pull_requests: false
