name: Report Flaky Tests

on:
    workflow_run:
        workflows: ['End-to-End Tests', 'End-to-End Tests Playwright']
        types:
            - completed

jobs:
    report-to-issues:
        name: Report to GitHub issues
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
              with:
                  ref: trunk

            - name: Use desired version of NodeJS
              uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install and build
              # TODO: We don't have to build the entire project, just the action itself.
              run: |
                  npm ci
                  npm run build:packages

            - name: Report flaky tests
              uses: ./packages/report-flaky-tests
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  label: '[Type] Flaky Test'
                  artifact-name-prefix: flaky-tests-report
