on: pull_request
name: Milestone merged pull requests
jobs:
  milestoneIt:
    name: Milestone It
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Milestone It
      uses: ./.github/actions/milestone-it
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
