on: pull_request
name: Assign fixed issues when pull request opened
jobs:
  filterOpened:
    name: Filter opened
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter opened
      uses: actions/bin/filter@0dbb077f64d0ec1068a644d25c71b1db66148a24
      with:
        args: action opened
    - name: Assign Fixed Issues
      uses: ./.github/actions/assign-fixed-issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
