on: pull_request
name: Assign fixed issues when pull request opened
jobs:
  filterOpened:
    name: Filter opened
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Assign Fixed Issues
      uses: ./.github/actions/assign-fixed-issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
