on: pull_request
name: Add the First-time Contributor label
jobs:
  filterOpened:
    name: Filter opened
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: First Time Contributor
      uses: ./.github/actions/first-time-contributor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
