name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: macos-12
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-rendering]
                api-level: [29]

        steps:
            - name: checkout
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Use desired version of Java
              uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
              with:
                  distribution: 'corretto'
                  java-version: '17'

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Gradle cache
              uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1

            - name: AVD cache
              uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
              id: avd-cache
              with:
                  path: |
                      ~/.android/avd/*
                      ~/.android/adb*
                  key: avd-${{ matrix.api-level }}

            - name: Create AVD and generate snapshot for caching
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b # v2.28.0
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: false
                  arch: x86_64
                  profile: Nexus 6
                  script: echo "Generated AVD snapshot for caching."

            - name: Run tests
              uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b # v2.28.0
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  arch: x86_64
                  profile: Nexus 6
                  script: npm run native test:e2e:android:local ${{ matrix.native-test-name }}

            - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: android-screen-recordings
                  path: packages/react-native-editor/android-screen-recordings

            - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
