name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

jobs:
    test:
        runs-on: macos-latest
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-initial-html]

        steps:
            - name: checkout
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Restore npm cache
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

            - run: npm ci

            - name: Restore Gradle cache
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

            - uses: reactivecircus/android-emulator-runner@d2799957d660add41c61a5103e2fbb9e2889eb73 # v2.15.0
              with:
                  api-level: 28
                  profile: pixel_xl
                  script: npm run native test:e2e:android:local ${{ matrix.native-test-name }}

            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: android-screen-recordings
                  path: packages/react-native-editor/android-screen-recordings

            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
