name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: macos-12
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-rendering]
                api-level: [29]

        steps:
<<<<<<< HEAD
          - name: CommentOut
            run: echo "workflow_was_comment_out"
#            - name: checkout
#              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
#
#            - name: Use desired version of NodeJS
#              uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.2.2
#              with:
#                  node-version: ${{ matrix.node }}
#                  cache: npm
#
#            - run: npm ci
#
#            - name: Restore Gradle cache
#              uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
#              with:
#                  path: ~/.gradle/caches
#                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#
#            - uses: reactivecircus/android-emulator-runner@d2799957d660add41c61a5103e2fbb9e2889eb73 # v2.15.0
#              with:
#                  api-level: 28
#                  profile: pixel_xl
#                  script: npm run native test:e2e:android:local ${{ matrix.native-test-name }}
#
#            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
#              if: always()
#              with:
#                  name: android-screen-recordings
#                  path: packages/react-native-editor/android-screen-recordings
#
#            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
#              if: always()
#              with:
#                  name: appium-logs
#                  path: packages/react-native-editor/appium-out.log
=======
            - name: checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Use desired version of Java
              uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
              with:
                  distribution: 'corretto'
                  java-version: '17'

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Restore tests setup cache
              uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
              with:
                  path: |
                      ~/.appium
                  key: ${{ runner.os }}-tests-setup-${{ hashFiles('package-lock.json') }}

            - name: Prepare tests setup
              run: npm run native test:e2e:setup

            - name: Gradle cache
              uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1

            - name: AVD cache
              uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
              id: avd-cache
              with:
                  path: |
                      ~/.android/avd/*
                      ~/.android/adb*
                  key: avd-${{ matrix.api-level }}

            - name: Create AVD and generate snapshot for caching
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@99a4aac18b4df9b3af66c4a1f04c1f23fa10c270 # v2.29.0
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: false
                  arch: x86_64
                  profile: Nexus 6
                  script: echo "Generated AVD snapshot for caching."

            - name: Run tests
              uses: reactivecircus/android-emulator-runner@99a4aac18b4df9b3af66c4a1f04c1f23fa10c270 # v2.29.0
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  arch: x86_64
                  profile: Nexus 6
                  script: npm run native test:e2e:android:local ${{ matrix.native-test-name }}

            - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
              if: always()
              with:
                  name: android-screen-recordings
                  path: packages/react-native-editor/android-screen-recordings

            - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
>>>>>>> upstream/trunk
