name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: macos-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-initial-html]

        steps:
            - name: checkout
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Use desired version of Java
              uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
              with:
                  distribution: 'temurin'
                  java-version: '11'
                  cache: 'gradle'

            - name: Use desired version of NodeJS
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - run: npm ci

            - name: Restore Gradle cache
              uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3.0.11
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

            - uses: reactivecircus/android-emulator-runner@d7b53ddc6e44254e1f4cf4a6ad67345837027a66 # v2.26.0
              with:
                  api-level: 28
                  emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160#issuecomment-868615730
                  profile: pixel_xl
                  script: npm run native test:e2e:android:local ${{ matrix.native-test-name }}

            - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
              if: always()
              with:
                  name: android-screen-recordings
                  path: packages/react-native-editor/android-screen-recordings

            - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
              if: always()
              with:
                  name: appium-logs
                  path: packages/react-native-editor/appium-out.log
