name: 'Mark old flaky tests issues as stale'
on:
    schedule:
        - cron: '20 1 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 # v6.0.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: 'This issue has gone 30 days without any activity.'
                  days-before-stale: 30
                  days-before-close: 1
                  only-labels: '[Type] Flaky Test'
                  stale-issue-label: '[Status] Stale'
