name: Storybook GitHub Pages

on:
    push:
        branches:
            - trunk

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - name: Checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
              with:
                  ref: trunk
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Build Storybook
              run: npm run storybook:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook/build
                  force_orphan: true
