name: Storybook GitHub Pages

on:
    push:
        branches:
            - trunk

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - name: Checkout
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  ref: trunk

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Build Storybook
              run: npm run storybook:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook/build
                  force_orphan: true
